ETAB
3613	01.07.1998	PROD	HLIQ  HWEF    BHPT 10 
--********************--
3635	01.04.2009	INJE	HWAT  HWEF    BHPT 500 
--********************--
3633	01.08.2008	PROD	HLIQ  HWEF    BHPT 10 
3633	14.06.2013	INJE	HWAT  HWEF    BHPT 500 
--********************--
3631	01.03.2008	PROD	HLIQ  HWEF    BHPT 10 
--********************--
3410	01.01.1998	PROD	HLIQ  HWEF    BHPT 10 
--********************--
3650	01.10.2008	PROD	HLIQ  HWEF    BHPT 10 
3650	13.12.2011	INJE	HWAT  HWEF    BHPT 500 
--********************--
220BTM	01.02.1993	PROD	HLIQ  HWEF    BHPT 10 
--********************--
225BTM	01.11.1997	PROD	HLIQ  HWEF    BHPT 10 
--********************--
224BTM	01.10.1991	PROD	HLIQ  HWEF    BHPT 10 
224BTM	01.03.1997	INJE	HWAT  HWEF    BHPT 500 
--********************--
3579	01.02.1996	PROD	HLIQ  HWEF    BHPT 10 
--********************--
3578	01.07.1996	PROD	HLIQ  HWEF    BHPT 10 
--********************--
3577	01.07.1996	PROD	HLIQ  HWEF    BHPT 10 
--********************--
3580	01.01.1996	PROD	HLIQ  HWEF    BHPT 10 
--********************--
3581	01.02.1996	PROD	HLIQ  HWEF    BHPT 10 
--********************--
3582	01.01.1996	PROD	HLIQ  HWEF    BHPT 10 
--********************--
3583	01.05.1997	PROD	HLIQ  HWEF    BHPT 10 
--********************--
3584	01.05.1997	PROD	HLIQ  HWEF    BHPT 10 
--********************--
3585	01.01.1998	PROD	HLIQ  HWEF    BHPT 10 
--********************--
3586	01.08.1997	PROD	HLIQ  HWEF    BHPT 10 
3586	21.07.2009	INJE	HWAT  HWEF    BHPT 500 
--********************--
3587	01.03.1998	PROD	HLIQ  HWEF    BHPT 10 
--********************--
3588	01.03.1998	PROD	HLIQ  HWEF    BHPT 10 
3588	18.08.1998	INJE	HWAT  HWEF    BHPT 500 
--********************--
3405	01.03.1997	PROD	HLIQ  HWEF    BHPT 10 
--********************--
3649	01.11.2008	PROD	HLIQ  HWEF    BHPT 10 
--********************--
3406	01.01.1998	PROD	HLIQ  HWEF    BHPT 10 
3406	01.09.2008	INJE	HWAT  HWEF    BHPT 500 
--********************--
3646	01.07.2008	PROD	HLIQ  HWEF    BHPT 10 
--********************--
3645	01.06.2008	PROD	HLIQ  HWEF    BHPT 10 
--********************--
3643	01.08.2008	PROD	HLIQ  HWEF    BHPT 10 
--********************--
3642	01.05.2008	PROD	HLIQ  HWEF    BHPT 10 
3642	11.03.2009	INJE	HWAT  HWEF    BHPT 500 
--********************--
216BTM	01.10.1991	PROD	HLIQ  HWEF    BHPT 10 
--********************--
ENDE
